larksuite/rsmpeg

- src/avformat/avformat.rs
- src/swresample/swresample.rs
- tests/transcode_aac.rs
Fix several documentation issues. Fix a bug in transcoding_aac test.
> Better SwrContext method

- src/avutil/samplefmt.rs
- src/swresample/swresample.rs
- tests/transcode_aac.rs
> Correct implementation of AVSamples

- src/avutil/rational.rs
> More docs to AVRatioanl apis

- src/avformat/avformat.rs
- tests/metadata.rs
> Revert some inaccurate change, Fix tests

- src/avformat/avformat.rs
Since `AVStream::metadata` is nullable, `metadata_mut()` won't always be useful.
> Add set_metadata() for `AVStream`

- src/avcodec/codec.rs
> Check if hwaccel enabled in `AVCodecContext`

- tests/avio_writing.rs
use AVFormatContextOutput::create function, create custom io, test
> Add avio_writing test

- src/lib.rs
> Export `UnsafeDerefMut`

- src/avcodec/packet.rs
- src/avutil/frame.rs
> impl `Send` for `AVPacket` and `AVFrame`

- tests/thumbnail.rs
> chore: simplify the code in thumbnail.rs

- CHANGELOG.md
- Cargo.toml
- README.md
- src/avcodec/codec.rs
> Bump version to 0.8.0

- CHANGELOG.md
- Cargo.toml
- README.md
Bump self&rusty_ffmpeg to 0.8.1
> Bump vesion to 0.8.1

- examples/shadertoy.rs
- src/avformat/avformat.rs
- tests/av_spliter.rs
- tests/avio_writing.rs
- tests/transcode_aac.rs
- tests/transcoding.rs
> Enable metadata dict specifying in `write_header`

- README.md
> Remove mention of examples folder in readme

- README.md
- src/avcodec/bitstream.rs
- src/avformat/avformat.rs
- tests/av_spliter.rs
- tests/avio_writing.rs
- tests/decode_audio.rs
- tests/extract_mvs.rs
- tests/image_dump.rs
- tests/metadata.rs
- tests/remux.rs
- tests/thumbnail.rs
- tests/transcode_aac.rs
- tests/transcoding.rs
- tests/tutorial01.rs
> Add `AVInputFomat::find`, make `AVFormatContextInput::open` accept format hint

- src/avutil/frame.rs
- src/avutil/mod.rs
- src/avutil/utils.rs
- tests/extract_mvs.rs
* Remove `AVFrame::get_motion_vectors`
* Add `get_media_type_string`
> Revise `extract_mvs` example

- src/avformat/avio.rs
So we can extract the data back after done writing
> add data getter in avio context custom

- src/macros.rs
> impl `Send` for macro generated reference types

- src/avformat/avio.rs
Add AVIOProtocol with methods to find protocol names and iterate through available input/output protocols. Includes tests to verify functionality.
> feat(avio): add protocol enumeration and name lookup

- CHANGELOG.md
- Cargo.toml
- doc/installed.md
- doc/source-build.md
- doc/vcpkg.md
- doc/winget.md
Update package version in Cargo.toml and all documentation files to reflect new release Add changelog entries for 0.17.0 features and changes
> Bump version to `0.17.0`
